Version 6

diff --git a/mygithub b/mygithub
--- a/mygithub
+++ b/mygithub
@@ -1,5 +1,9 @@
 #!/bin/bash
 #
+# Verion 6
+# - improve third option input.
+#   it's set now to "justme".
+#
 # Version 5
 # - support mirroring only repositories from given username
 # e.g. $ ./mygithub markuman /mnt/GITHUB/ justme
@@ -27,7 +31,7 @@
 # USAGE
 #
 #	$ chmod u+x mygithub
-#	$ ./mygithub markuman myGITHUBfavs
+#	$ ./mygithub markuman ~/GITHUB
 #	...
 #	$ ls myGITHUBfavs/
 #	aeolianine  arasbm  dac922     devsnd  elecay    hoytech     kaosat-dev  lukasepple  silentbicycle  stetro    waalt    yexiaobo-seeedstudio
@@ -36,12 +40,13 @@
 #	$ ./mygithub markuman /srv/http/viewgit/my-github-mirror/ justme
 #
 
+set -e
 
 if (("$#" < 2)); then
 	echo -e "Error: At least 2 arguments are needed. Your Github-Username and a destination dir.\n"
 elif (("$#" > 3)); then
-	echo -e "Error: Too much input arguments. Just 2 are needed. Github-Username and a destination dir.\n"
-elif (("$#" == 2)); then
+	echo -e "Error: Too much input arguments. Just 2 or 3 are needed. Github-Username and a destination dir.\n"
+else
 	# where am i?
 	currentdir=$(pwd)
 	# create temporary dir
@@ -58,58 +63,23 @@ elif (("$#" == 2)); then
 
 	echo "Using tmpdir $tmpdir"
 	# get the source...
-	wget -qP $tmpdir https://github.com/stars/$githubuser/
-	wget -qP $tmpdir https://github.com/$githubuser?tab=repositories
-
-	# extract only the repo urls
-	grep "<h3>" $tmpdir/index.html > $tmpdir/gits.raw
-	sed -n "/<h3 class=\"repolist-name\">/,/h3>/"p $tmpdir/$githubuser\?tab\=repositories >> $tmpdir/gits.raw
-	grep -o -E 'href="([^"#]+)"' $tmpdir/gits.raw | cut -d'"' -f2 > $tmpdir/gits.url
-
-	filename=$tmpdir/gits.url
-	while read -r line
-	do
-	    name=$line
-
-	    # if github repository folder don't exist -> clone
-	    if [ ! -d $destdir$name ]; then
-   	    	echo -e "\n\n Start cloning $name \n"
-	    	git clone https://github.com$name.git $destdir$name
-	    # if folder already exist -> pull
-	    else 
-		echo -e "\n\n Pull $name \n"
-		cd $destdir$name && git pull
-		cd $currentdir
-	    fi
-	done < "$filename"
-
-	# delete tmpdir
-	rm -r $tmpdir
-	
-# mygithub markuman destination/dir/ mirror
-# add least, it doesn't matter what string the third option is! :)
-elif (("$#" == 3)); then
-	# where am i?
-	currentdir=$(pwd)
-	# create temporary dir
-	tmpdir=$(mktemp -d)
-
-	# username + destination dir.
-	githubuser=$1
-	destdir=$2
-
-	# destdir check
-	if [ ! -d $destdir ]; then
-		mkdir -p $destdir
+	if (("$#" == 3)); then
+		if [[ "$3" = "justme" ]]; then
+			wget -qP $tmpdir https://github.com/$githubuser?tab=repositories
+			sed -n "/<h3 class=\"repolist-name\">/,/h3>/"p $tmpdir/$githubuser\?tab\=repositories >> $tmpdir/gits.raw
+			grep -o -E 'href="([^"#]+)"' $tmpdir/gits.raw | cut -d'"' -f2 > $tmpdir/gits.url
+		else
+			echo -e "\nError: Unknown third option!\n"
+			rmdir $tmpdir
+			exit 1
+		fi
+	else
+		wget -qP $tmpdir https://github.com/stars/$githubuser/
+		wget -qP $tmpdir https://github.com/$githubuser?tab=repositories
+		grep "<h3>" $tmpdir/index.html > $tmpdir/gits.raw
+		sed -n "/<h3 class=\"repolist-name\">/,/h3>/"p $tmpdir/$githubuser\?tab\=repositories >> $tmpdir/gits.raw
+		grep -o -E 'href="([^"#]+)"' $tmpdir/gits.raw | cut -d'"' -f2 > $tmpdir/gits.url
 	fi
-
-	echo "Using tmpdir $tmpdir"
-	# get the source...
-	wget -qP $tmpdir https://github.com/$githubuser?tab=repositories
-
-	# extract only the repo urls
-	sed -n "/<h3 class=\"repolist-name\">/,/h3>/"p $tmpdir/$githubuser\?tab\=repositories > $tmpdir/gits.raw
-	grep -o -E 'href="([^"#]+)"' $tmpdir/gits.raw | cut -d'"' -f2 > $tmpdir/gits.url
 
 	filename=$tmpdir/gits.url
 	while read -r line
